"""Add source_user_id and source_filename to records table

Revision ID: 483f3c9c5048
Revises: 
Create Date: 2025-12-19 12:47:13.380135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483f3c9c5048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_filename', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_records_source_filename'), ['source_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_source_user_id'), ['source_user_id'], unique=False)
        batch_op.create_foreign_key('fk_records_source_user', 'users', ['source_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_records_source_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_records_source_user_id'))
        batch_op.drop_index(batch_op.f('ix_records_source_filename'))
        batch_op.drop_column('source_filename')
        batch_op.drop_column('source_user_id')

    # ### end Alembic commands ###
